update artifact5

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -51,6 +51,8 @@ jobs:
         run: |
           echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
           hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
+      - name: Check if public directory exists  # ✅ public/ 디렉토리 확인
+        run: ls -la ./public || echo "❌ public directory not found!"
       - name: Upload artifact
         uses: actions/upload-artifact@v4
         with:
@@ -71,19 +73,8 @@ jobs:
         with:
           name: my-artifact
           path: ./public
-
+      - name: Check downloaded files
+        run: ls -la ./public || echo "❌ public directory is missing after download!"
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v2
-
-  # deploy:
-  #   if: github.repository_owner != 'HugoBlox'
-  #   environment:
-  #     name: github-pages
-  #     url: ${{ steps.deployment.outputs.page_url }}
-  #   runs-on: ubuntu-latest
-  #   needs: build
-  #   steps:
-  #     - name: Deploy to GitHub Pages
-  #       id: deployment
-  #       uses: actions/deploy-pages@v2
