update publish.yaml3

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -51,12 +51,13 @@ jobs:
         run: |
           echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
           hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
-      - name: Check if public directory exists  # ✅ public/ 디렉토리 확인
-        run: ls -la ./public || echo "❌ public directory not found!"
+      # - name: Check if public directory exists  # ✅ public/ 디렉토리 확인
+      #   run: ls -la ./public || echo "❌ public directory not found!"
+
       - name: Upload artifact
-        uses: actions/upload-artifact@v3
-        with:
-          path: ./public
+        uses: actions/upload-artifact@v4
+        # with:
+        #   path: ./public
 
   # Deploy website to GitHub Pages hosting
   deploy:
@@ -67,6 +68,12 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
-    - name: Deploy to GitHub Pages
-      id: deployment
-      uses: actions/deploy-pages@v4
+      - uses: actions/download-artifact@v4
+        with:
+          name: my-artifact
+      - name: Display structure of downloaded files
+        run: ls -R
+        
+    # - name: Deploy to GitHub Pages
+    #   id: deployment
+    #   uses: actions/deploy-pages@v4
